// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.ts"
import type { Client, Options as Options2, TDataShape } from "./client/index.ts"
import type {
  CreateData,
  CreateResponses,
  DeleteData,
  DeleteResponses,
  FindByIdData,
  FindByIdResponses,
  FindReleaseData,
  FindReleaseResponses,
  LatestReleaseData,
  LatestReleaseResponses,
  ListAll1Data,
  ListAll1Responses,
  ListAllData,
  ListAllResponses,
  PublishReleaseData,
  PublishReleaseResponses,
} from "./types.gen.ts"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

export const listAll = <ThrowOnError extends boolean = false>(
  options?: Options<ListAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListAllResponses, unknown, ThrowOnError>({
    url: "/api/admin/artifacts",
    ...options,
  })

export const create = <ThrowOnError extends boolean = false>(
  options: Options<CreateData, ThrowOnError>
) =>
  (options.client ?? client).post<CreateResponses, unknown, ThrowOnError>({
    url: "/api/admin/artifacts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const publishRelease = <ThrowOnError extends boolean = false>(
  options: Options<PublishReleaseData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PublishReleaseResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/admin/artifacts/{id}/releases",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const listAll1 = <ThrowOnError extends boolean = false>(
  options?: Options<ListAll1Data, ThrowOnError>
) =>
  (options?.client ?? client).get<ListAll1Responses, unknown, ThrowOnError>({
    url: "/api/admin/users",
    ...options,
  })

export const delete_ = <ThrowOnError extends boolean = false>(
  options: Options<DeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteResponses, unknown, ThrowOnError>({
    url: "/api/admin/artifacts/{id}",
    ...options,
  })

export const findById = <ThrowOnError extends boolean = false>(
  options: Options<FindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<FindByIdResponses, unknown, ThrowOnError>({
    url: "/api/admin/artifacts/{id}",
    ...options,
  })

export const findRelease = <ThrowOnError extends boolean = false>(
  options: Options<FindReleaseData, ThrowOnError>
) =>
  (options.client ?? client).get<FindReleaseResponses, unknown, ThrowOnError>({
    url: "/api/admin/artifacts/{id}/releases/{version}",
    ...options,
  })

export const latestRelease = <ThrowOnError extends boolean = false>(
  options: Options<LatestReleaseData, ThrowOnError>
) =>
  (options.client ?? client).get<LatestReleaseResponses, unknown, ThrowOnError>(
    { url: "/api/admin/artifacts/{id}/releases/latest", ...options }
  )
