// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {})
}

export type CreateArtifactRequest = {
  name?: string
}

export type ArtifactBinaryDto = {
  platform?: string
  downloadUrl?: string
  hashAlgorithm?: string
  hashValue?: string
  sizeBytes?: number
  signature?: string
}

export type ArtifactDto = {
  id?: string
  artifactName?: string
  releases?: Array<ReleaseDto>
}

export type ReleaseDto = {
  releaseId?: string
  version?: string
  publishedAt?: string
  binaries?: Array<ArtifactBinaryDto>
}

export type BinaryEntry = {
  platform?: string
  downloadUrl?: string
  hashAlgorithm?: string
  hashValue?: string
  sizeBytes?: number
  signature?: string
}

export type PublishReleaseRequest = {
  version?: string
  binaries?: Array<BinaryEntry>
}

export type UserDto = {
  id?: UserId
  name?: string
  email?: string
  picture?: string
  role?: "USER" | "ADMIN"
  createdAt?: string
  lastLoginAt?: string
}

export type UserId = unknown

export type ListAllData = {
  body?: never
  path?: never
  query?: never
  url: "/api/admin/artifacts"
}

export type ListAllResponses = {
  /**
   * OK
   */
  200: Array<ArtifactDto>
}

export type ListAllResponse = ListAllResponses[keyof ListAllResponses]

export type CreateData = {
  body: CreateArtifactRequest
  path?: never
  query?: never
  url: "/api/admin/artifacts"
}

export type CreateResponses = {
  /**
   * OK
   */
  200: ArtifactDto
}

export type CreateResponse = CreateResponses[keyof CreateResponses]

export type PublishReleaseData = {
  body: PublishReleaseRequest
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/artifacts/{id}/releases"
}

export type PublishReleaseResponses = {
  /**
   * OK
   */
  200: ReleaseDto
}

export type PublishReleaseResponse =
  PublishReleaseResponses[keyof PublishReleaseResponses]

export type ListAll1Data = {
  body?: never
  path?: never
  query?: never
  url: "/api/admin/users"
}

export type ListAll1Responses = {
  /**
   * OK
   */
  200: Array<UserDto>
}

export type ListAll1Response = ListAll1Responses[keyof ListAll1Responses]

export type DeleteData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/artifacts/{id}"
}

export type DeleteResponses = {
  /**
   * OK
   */
  200: unknown
}

export type FindByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/artifacts/{id}"
}

export type FindByIdResponses = {
  /**
   * OK
   */
  200: ArtifactDto
}

export type FindByIdResponse = FindByIdResponses[keyof FindByIdResponses]

export type FindReleaseData = {
  body?: never
  path: {
    id: string
    version: string
  }
  query?: never
  url: "/api/admin/artifacts/{id}/releases/{version}"
}

export type FindReleaseResponses = {
  /**
   * OK
   */
  200: ReleaseDto
}

export type FindReleaseResponse =
  FindReleaseResponses[keyof FindReleaseResponses]

export type LatestReleaseData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/artifacts/{id}/releases/latest"
}

export type LatestReleaseResponses = {
  /**
   * OK
   */
  200: ReleaseDto
}

export type LatestReleaseResponse =
  LatestReleaseResponses[keyof LatestReleaseResponses]
