// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.ts"
import type { Client, Options as Options2, TDataShape } from "./client/index.ts"
import type {
  CreateData,
  CreateResponses,
  GetEndpointsData,
  GetEndpointsResponses,
  GetRawJsonData,
  GetRawJsonResponses,
  GetSummaryData,
  GetSummaryResponses,
  ListAllData,
  ListAllResponses,
  UpdateData,
  UpdateResponses,
} from "./types.gen.ts"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

export const update = <ThrowOnError extends boolean = false>(
  options: Options<UpdateData, ThrowOnError>
) =>
  (options.client ?? client).put<UpdateResponses, unknown, ThrowOnError>({
    url: "/api/openapi-docs/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const listAll = <ThrowOnError extends boolean = false>(
  options?: Options<ListAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListAllResponses, unknown, ThrowOnError>({
    url: "/api/openapi-docs",
    ...options,
  })

export const create = <ThrowOnError extends boolean = false>(
  options: Options<CreateData, ThrowOnError>
) =>
  (options.client ?? client).post<CreateResponses, unknown, ThrowOnError>({
    url: "/api/openapi-docs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getSummary = <ThrowOnError extends boolean = false>(
  options: Options<GetSummaryData, ThrowOnError>
) =>
  (options.client ?? client).get<GetSummaryResponses, unknown, ThrowOnError>({
    url: "/api/openapi-docs/{id}/summary",
    ...options,
  })

export const getRawJson = <ThrowOnError extends boolean = false>(
  options: Options<GetRawJsonData, ThrowOnError>
) =>
  (options.client ?? client).get<GetRawJsonResponses, unknown, ThrowOnError>({
    url: "/api/openapi-docs/{id}/raw",
    ...options,
  })

export const getEndpoints = <ThrowOnError extends boolean = false>(
  options: Options<GetEndpointsData, ThrowOnError>
) =>
  (options.client ?? client).get<GetEndpointsResponses, unknown, ThrowOnError>({
    url: "/api/openapi-docs/{id}/endpoints",
    ...options,
  })
