// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:5050" | (string & {})
}

export type UpdateRawJsonRequest = {
  rawJson?: string
}

export type CreateOpenApiDocsCommand = {
  serviceName?: string
  rawJson?: string
}

export type OpenApiDocSummary = {
  id?: number
  serviceName?: string
  version?: number
  hash?: string
}

export type OpenApiSummaryDto = {
  title?: string
  version?: string
  description?: string
  totalEndpoints?: number
  tags?: Array<string>
}

export type EndpointDto = {
  summary?: EndpointSummaryDto
  endpoints?: Array<EndpointItemDto>
}

export type EndpointItemDto = {
  path?: string
  method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS"
  operationId?: string
  summary?: string
  description?: string
  parameters?: Array<EndpointParameter>
  requestBody?: EndpointRequestBodyDto
  responses?: Array<EndpointResponseBodyDto>
  tags?: Array<string>
}

export type EndpointParameter = {
  name?: string
  location?: "PATH" | "QUERY" | "HEADER" | "COOKIE"
  type?: string
  required?: boolean
}

export type EndpointRequestBodyDto = {
  mediaType?: string
  schemaJson?: string
  required?: boolean
}

export type EndpointResponseBodyDto = {
  statusCode?: number
  mediaType?: string
  schemaJson?: string
  description?: string
}

export type EndpointSummaryDto = {
  docId?: OpenApiDocId
  totalEndpoints?: number
}

export type OpenApiDocId = {
  value?: number
}

export type UpdateData = {
  body: UpdateRawJsonRequest
  path: {
    id: number
  }
  query?: never
  url: "/api/openapi-docs/{id}"
}

export type UpdateResponses = {
  /**
   * OK
   */
  200: unknown
}

export type ListAllData = {
  body?: never
  path?: never
  query?: never
  url: "/api/openapi-docs"
}

export type ListAllResponses = {
  /**
   * OK
   */
  200: Array<OpenApiDocSummary>
}

export type ListAllResponse = ListAllResponses[keyof ListAllResponses]

export type CreateData = {
  body: CreateOpenApiDocsCommand
  path?: never
  query?: never
  url: "/api/openapi-docs"
}

export type CreateResponses = {
  /**
   * OK
   */
  200: unknown
}

export type GetSummaryData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: "/api/openapi-docs/{id}/summary"
}

export type GetSummaryResponses = {
  /**
   * OK
   */
  200: OpenApiSummaryDto
}

export type GetSummaryResponse = GetSummaryResponses[keyof GetSummaryResponses]

export type GetRawJsonData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: "/api/openapi-docs/{id}/raw"
}

export type GetRawJsonResponses = {
  /**
   * OK
   */
  200: string
}

export type GetRawJsonResponse = GetRawJsonResponses[keyof GetRawJsonResponses]

export type GetEndpointsData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: "/api/openapi-docs/{id}/endpoints"
}

export type GetEndpointsResponses = {
  /**
   * OK
   */
  200: EndpointDto
}

export type GetEndpointsResponse =
  GetEndpointsResponses[keyof GetEndpointsResponses]
