// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query"

import { client } from "../client.gen.ts"
import {
  create,
  delete_,
  findById,
  findRelease,
  latestRelease,
  listAll,
  listAll1,
  type Options,
  publishRelease,
} from "../sdk.gen.ts"
import type {
  CreateData,
  CreateResponse,
  DeleteData,
  FindByIdData,
  FindByIdResponse,
  FindReleaseData,
  FindReleaseResponse,
  LatestReleaseData,
  LatestReleaseResponse,
  ListAll1Data,
  ListAll1Response,
  ListAllData,
  ListAllResponse,
  PublishReleaseData,
  PublishReleaseResponse,
} from "../types.gen.ts"

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const listAllQueryKey = (options?: Options<ListAllData>) =>
  createQueryKey("listAll", options)

export const listAllOptions = (options?: Options<ListAllData>) =>
  queryOptions<
    ListAllResponse,
    DefaultError,
    ListAllResponse,
    ReturnType<typeof listAllQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listAllQueryKey(options),
  })

export const createMutation = (
  options?: Partial<Options<CreateData>>
): UseMutationOptions<CreateResponse, DefaultError, Options<CreateData>> => {
  const mutationOptions: UseMutationOptions<
    CreateResponse,
    DefaultError,
    Options<CreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await create({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const publishReleaseMutation = (
  options?: Partial<Options<PublishReleaseData>>
): UseMutationOptions<
  PublishReleaseResponse,
  DefaultError,
  Options<PublishReleaseData>
> => {
  const mutationOptions: UseMutationOptions<
    PublishReleaseResponse,
    DefaultError,
    Options<PublishReleaseData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await publishRelease({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listAll1QueryKey = (options?: Options<ListAll1Data>) =>
  createQueryKey("listAll1", options)

export const listAll1Options = (options?: Options<ListAll1Data>) =>
  queryOptions<
    ListAll1Response,
    DefaultError,
    ListAll1Response,
    ReturnType<typeof listAll1QueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAll1({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listAll1QueryKey(options),
  })

export const deleteMutation = (
  options?: Partial<Options<DeleteData>>
): UseMutationOptions<unknown, DefaultError, Options<DeleteData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<DeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await delete_({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const findByIdQueryKey = (options: Options<FindByIdData>) =>
  createQueryKey("findById", options)

export const findByIdOptions = (options: Options<FindByIdData>) =>
  queryOptions<
    FindByIdResponse,
    DefaultError,
    FindByIdResponse,
    ReturnType<typeof findByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await findById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: findByIdQueryKey(options),
  })

export const findReleaseQueryKey = (options: Options<FindReleaseData>) =>
  createQueryKey("findRelease", options)

export const findReleaseOptions = (options: Options<FindReleaseData>) =>
  queryOptions<
    FindReleaseResponse,
    DefaultError,
    FindReleaseResponse,
    ReturnType<typeof findReleaseQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await findRelease({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: findReleaseQueryKey(options),
  })

export const latestReleaseQueryKey = (options: Options<LatestReleaseData>) =>
  createQueryKey("latestRelease", options)

export const latestReleaseOptions = (options: Options<LatestReleaseData>) =>
  queryOptions<
    LatestReleaseResponse,
    DefaultError,
    LatestReleaseResponse,
    ReturnType<typeof latestReleaseQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await latestRelease({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: latestReleaseQueryKey(options),
  })
