spring.application.name=devcom-server
server.port=5050

spring.config.import=optional:file:${user.home}/.devcom/config.properties
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m
