# SQLite persistent database
spring.datasource.url=jdbc:sqlite:${user.home}/.devcom/devcom.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=false

server.port=0

app.remote-server.url=https://api.devscentral.com/

