spring.application.name=command-center-local
server.port=5050

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m

spring.profiles.default=dev

