// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query"

import { client } from "../client.gen.ts"
import {
  create,
  getEndpoints,
  getRawJson,
  getSummary,
  listAll,
  type Options,
  update,
} from "../sdk.gen.ts"
import type {
  CreateData,
  GetEndpointsData,
  GetEndpointsResponse,
  GetRawJsonData,
  GetRawJsonResponse,
  GetSummaryData,
  GetSummaryResponse,
  ListAllData,
  ListAllResponse,
  UpdateData,
} from "../types.gen.ts"

export const updateMutation = (
  options?: Partial<Options<UpdateData>>
): UseMutationOptions<unknown, DefaultError, Options<UpdateData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<UpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await update({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const listAllQueryKey = (options?: Options<ListAllData>) =>
  createQueryKey("listAll", options)

export const listAllOptions = (options?: Options<ListAllData>) =>
  queryOptions<
    ListAllResponse,
    DefaultError,
    ListAllResponse,
    ReturnType<typeof listAllQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listAllQueryKey(options),
  })

export const createMutation = (
  options?: Partial<Options<CreateData>>
): UseMutationOptions<unknown, DefaultError, Options<CreateData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<CreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await create({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getSummaryQueryKey = (options: Options<GetSummaryData>) =>
  createQueryKey("getSummary", options)

export const getSummaryOptions = (options: Options<GetSummaryData>) =>
  queryOptions<
    GetSummaryResponse,
    DefaultError,
    GetSummaryResponse,
    ReturnType<typeof getSummaryQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSummary({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getSummaryQueryKey(options),
  })

export const getRawJsonQueryKey = (options: Options<GetRawJsonData>) =>
  createQueryKey("getRawJson", options)

export const getRawJsonOptions = (options: Options<GetRawJsonData>) =>
  queryOptions<
    GetRawJsonResponse,
    DefaultError,
    GetRawJsonResponse,
    ReturnType<typeof getRawJsonQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRawJson({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getRawJsonQueryKey(options),
  })

export const getEndpointsQueryKey = (options: Options<GetEndpointsData>) =>
  createQueryKey("getEndpoints", options)

export const getEndpointsOptions = (options: Options<GetEndpointsData>) =>
  queryOptions<
    GetEndpointsResponse,
    DefaultError,
    GetEndpointsResponse,
    ReturnType<typeof getEndpointsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEndpoints({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getEndpointsQueryKey(options),
  })
