// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.ts"
import type { Client, Options as Options2, TDataShape } from "./client/index.ts"
import type {
  CheckUpdate1Data,
  CheckUpdate1Responses,
  CheckUpdateData,
  CheckUpdateResponses,
  DesktopLoginData,
  DesktopLoginResponses,
} from "./types.gen.ts"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

export const checkUpdate = <ThrowOnError extends boolean = false>(
  options?: Options<CheckUpdateData, ThrowOnError>
) =>
  (options?.client ?? client).get<CheckUpdateResponses, unknown, ThrowOnError>({
    url: "/api/public/local/cicd/check",
    ...options,
  })

export const checkUpdate1 = <ThrowOnError extends boolean = false>(
  options: Options<CheckUpdate1Data, ThrowOnError>
) =>
  (options.client ?? client).get<CheckUpdate1Responses, unknown, ThrowOnError>({
    url: "/api/public/desktop/cicd/{target}/{arch}/{currentVersion}",
    ...options,
  })

export const desktopLogin = <ThrowOnError extends boolean = false>(
  options: Options<DesktopLoginData, ThrowOnError>
) =>
  (options.client ?? client).get<DesktopLoginResponses, unknown, ThrowOnError>({
    url: "/api/public/auth/desktop",
    ...options,
  })
