// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {})
}

export type UpdateCheckResponse = {
  version?: string
  downloadUrl?: string
  hashAlgorithm?: string
  hashValue?: string
  sizeBytes?: number
}

export type TauriUpdateResponse = {
  version?: string
  url?: string
  signature?: string
  notes?: string
  pub_date?: string
}

export type ApplicationContext = {
  parent?: ApplicationContext
  id?: string
  displayName?: string
  autowireCapableBeanFactory?: AutowireCapableBeanFactory
  applicationName?: string
  startupDate?: number
  environment?: Environment
  beanDefinitionCount?: number
  beanDefinitionNames?: Array<string>
  parentBeanFactory?: BeanFactory
  classLoader?: {
    name?: string
    registeredAsParallelCapable?: boolean
    parent?: {
      name?: string
      registeredAsParallelCapable?: boolean
      unnamedModule?: {
        name?: string
        descriptor?: {
          open?: boolean
          automatic?: boolean
        }
        named?: boolean
        annotations?: Array<unknown>
        declaredAnnotations?: Array<unknown>
        packages?: Array<string>
        nativeAccessEnabled?: boolean
        layer?: unknown
      }
      definedPackages?: Array<{
        name?: string
        sealed?: boolean
        annotations?: Array<unknown>
        declaredAnnotations?: Array<unknown>
        specificationTitle?: string
        specificationVersion?: string
        specificationVendor?: string
        implementationTitle?: string
        implementationVersion?: string
        implementationVendor?: string
      }>
    }
    unnamedModule?: {
      name?: string
      descriptor?: {
        open?: boolean
        automatic?: boolean
      }
      named?: boolean
      annotations?: Array<unknown>
      declaredAnnotations?: Array<unknown>
      packages?: Array<string>
      nativeAccessEnabled?: boolean
      layer?: unknown
    }
    definedPackages?: Array<{
      name?: string
      sealed?: boolean
      annotations?: Array<unknown>
      declaredAnnotations?: Array<unknown>
      specificationTitle?: string
      specificationVersion?: string
      specificationVendor?: string
      implementationTitle?: string
      implementationVersion?: string
      implementationVendor?: string
    }>
  }
}

export type AutowireCapableBeanFactory = unknown

export type BeanFactory = unknown

export type DefaultHttpStatusCode = HttpStatusCode

export type Environment = {
  defaultProfiles?: Array<string>
  activeProfiles?: Array<string>
}

export type FilterRegistration = {
  servletNameMappings?: Array<string>
  urlPatternMappings?: Array<string>
  name?: string
  className?: string
  initParameters?: {
    [key: string]: string
  }
}

export type HttpStatus =
  | "100 CONTINUE"
  | "101 SWITCHING_PROTOCOLS"
  | "102 PROCESSING"
  | "103 EARLY_HINTS"
  | "200 OK"
  | "201 CREATED"
  | "202 ACCEPTED"
  | "203 NON_AUTHORITATIVE_INFORMATION"
  | "204 NO_CONTENT"
  | "205 RESET_CONTENT"
  | "206 PARTIAL_CONTENT"
  | "207 MULTI_STATUS"
  | "208 ALREADY_REPORTED"
  | "226 IM_USED"
  | "300 MULTIPLE_CHOICES"
  | "301 MOVED_PERMANENTLY"
  | "302 FOUND"
  | "303 SEE_OTHER"
  | "304 NOT_MODIFIED"
  | "307 TEMPORARY_REDIRECT"
  | "308 PERMANENT_REDIRECT"
  | "400 BAD_REQUEST"
  | "401 UNAUTHORIZED"
  | "402 PAYMENT_REQUIRED"
  | "403 FORBIDDEN"
  | "404 NOT_FOUND"
  | "405 METHOD_NOT_ALLOWED"
  | "406 NOT_ACCEPTABLE"
  | "407 PROXY_AUTHENTICATION_REQUIRED"
  | "408 REQUEST_TIMEOUT"
  | "409 CONFLICT"
  | "410 GONE"
  | "411 LENGTH_REQUIRED"
  | "412 PRECONDITION_FAILED"
  | "413 CONTENT_TOO_LARGE"
  | "413 PAYLOAD_TOO_LARGE"
  | "414 URI_TOO_LONG"
  | "415 UNSUPPORTED_MEDIA_TYPE"
  | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
  | "417 EXPECTATION_FAILED"
  | "418 I_AM_A_TEAPOT"
  | "421 MISDIRECTED_REQUEST"
  | "422 UNPROCESSABLE_CONTENT"
  | "422 UNPROCESSABLE_ENTITY"
  | "423 LOCKED"
  | "424 FAILED_DEPENDENCY"
  | "425 TOO_EARLY"
  | "426 UPGRADE_REQUIRED"
  | "428 PRECONDITION_REQUIRED"
  | "429 TOO_MANY_REQUESTS"
  | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
  | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
  | "500 INTERNAL_SERVER_ERROR"
  | "501 NOT_IMPLEMENTED"
  | "502 BAD_GATEWAY"
  | "503 SERVICE_UNAVAILABLE"
  | "504 GATEWAY_TIMEOUT"
  | "505 HTTP_VERSION_NOT_SUPPORTED"
  | "506 VARIANT_ALSO_NEGOTIATES"
  | "507 INSUFFICIENT_STORAGE"
  | "508 LOOP_DETECTED"
  | "509 BANDWIDTH_LIMIT_EXCEEDED"
  | "510 NOT_EXTENDED"
  | "511 NETWORK_AUTHENTICATION_REQUIRED"

export type HttpStatusCode = {
  error?: boolean
  is5xxServerError?: boolean
  is4xxClientError?: boolean
  is2xxSuccessful?: boolean
  is3xxRedirection?: boolean
  is1xxInformational?: boolean
}

export type JspConfigDescriptor = {
  jspPropertyGroups?: Array<JspPropertyGroupDescriptor>
  taglibs?: Array<TaglibDescriptor>
}

export type JspPropertyGroupDescriptor = {
  buffer?: string
  defaultContentType?: string
  urlPatterns?: Array<string>
  isXml?: string
  trimDirectiveWhitespaces?: string
  errorOnUndeclaredNamespace?: string
  deferredSyntaxAllowedAsLiteral?: string
  elIgnored?: string
  includeCodas?: Array<string>
  errorOnELNotFound?: string
  pageEncoding?: string
  scriptingInvalid?: string
  includePreludes?: Array<string>
}

export type RedirectView = {
  applicationContext?: ApplicationContext
  contentType?: string
  requestContextAttribute?: string
  exposePathVariables?: boolean
  beanName?: string
  url?: string
  hosts?: Array<string>
  redirectView?: boolean
  propagateQueryProperties?: boolean
}

export type ServletContext = {
  classLoader?: {
    name?: string
    registeredAsParallelCapable?: boolean
    parent?: {
      name?: string
      registeredAsParallelCapable?: boolean
      unnamedModule?: {
        name?: string
        descriptor?: {
          open?: boolean
          automatic?: boolean
        }
        named?: boolean
        annotations?: Array<unknown>
        declaredAnnotations?: Array<unknown>
        packages?: Array<string>
        nativeAccessEnabled?: boolean
        layer?: unknown
      }
      definedPackages?: Array<{
        name?: string
        sealed?: boolean
        annotations?: Array<unknown>
        declaredAnnotations?: Array<unknown>
        specificationTitle?: string
        specificationVersion?: string
        specificationVendor?: string
        implementationTitle?: string
        implementationVersion?: string
        implementationVendor?: string
      }>
    }
    unnamedModule?: {
      name?: string
      descriptor?: {
        open?: boolean
        automatic?: boolean
      }
      named?: boolean
      annotations?: Array<unknown>
      declaredAnnotations?: Array<unknown>
      packages?: Array<string>
      nativeAccessEnabled?: boolean
      layer?: unknown
    }
    definedPackages?: Array<{
      name?: string
      sealed?: boolean
      annotations?: Array<unknown>
      declaredAnnotations?: Array<unknown>
      specificationTitle?: string
      specificationVersion?: string
      specificationVendor?: string
      implementationTitle?: string
      implementationVersion?: string
      implementationVendor?: string
    }>
  }
  majorVersion?: number
  minorVersion?: number
  initParameterNames?: unknown
  contextPath?: string
  requestCharacterEncoding?: string
  responseCharacterEncoding?: string
  effectiveSessionTrackingModes?: Array<"COOKIE" | "URL" | "SSL">
  defaultSessionTrackingModes?: Array<"COOKIE" | "URL" | "SSL">
  effectiveMinorVersion?: number
  effectiveMajorVersion?: number
  sessionCookieConfig?: SessionCookieConfig
  filterRegistrations?: {
    [key: string]: FilterRegistration
  }
  servletContextName?: string
  servletRegistrations?: {
    [key: string]: ServletRegistration
  }
  jspConfigDescriptor?: JspConfigDescriptor
  serverInfo?: string
  sessionTimeout?: number
  virtualServerName?: string
  attributeNames?: unknown
}

export type ServletRegistration = {
  mappings?: Array<string>
  runAsRole?: string
  name?: string
  className?: string
  initParameters?: {
    [key: string]: string
  }
}

export type SessionCookieConfig = {
  name?: string
  path?: string
  attributes?: {
    [key: string]: string
  }
  /**
   * @deprecated
   */
  comment?: string
  secure?: boolean
  maxAge?: number
  httpOnly?: boolean
  domain?: string
}

export type TaglibDescriptor = {
  taglibURI?: string
  taglibLocation?: string
}

export type ApplicationContextWritable = {
  parent?: ApplicationContextWritable
  id?: string
  displayName?: string
  autowireCapableBeanFactory?: AutowireCapableBeanFactory
  applicationName?: string
  startupDate?: number
  environment?: Environment
  beanDefinitionCount?: number
  beanDefinitionNames?: Array<string>
  parentBeanFactory?: BeanFactory
  classLoader?: {
    name?: string
    registeredAsParallelCapable?: boolean
    parent?: {
      name?: string
      registeredAsParallelCapable?: boolean
      unnamedModule?: {
        name?: string
        descriptor?: {
          open?: boolean
          automatic?: boolean
        }
        named?: boolean
        annotations?: Array<unknown>
        declaredAnnotations?: Array<unknown>
        packages?: Array<string>
        nativeAccessEnabled?: boolean
        layer?: unknown
      }
      definedPackages?: Array<{
        name?: string
        sealed?: boolean
        annotations?: Array<unknown>
        declaredAnnotations?: Array<unknown>
        specificationTitle?: string
        specificationVersion?: string
        specificationVendor?: string
        implementationTitle?: string
        implementationVersion?: string
        implementationVendor?: string
      }>
      defaultAssertionStatus?: boolean
    }
    unnamedModule?: {
      name?: string
      descriptor?: {
        open?: boolean
        automatic?: boolean
      }
      named?: boolean
      annotations?: Array<unknown>
      declaredAnnotations?: Array<unknown>
      packages?: Array<string>
      nativeAccessEnabled?: boolean
      layer?: unknown
    }
    definedPackages?: Array<{
      name?: string
      sealed?: boolean
      annotations?: Array<unknown>
      declaredAnnotations?: Array<unknown>
      specificationTitle?: string
      specificationVersion?: string
      specificationVendor?: string
      implementationTitle?: string
      implementationVersion?: string
      implementationVendor?: string
    }>
    defaultAssertionStatus?: boolean
  }
}

export type RedirectViewWritable = {
  applicationContext?: ApplicationContextWritable
  servletContext?: ServletContextWritable
  contentType?: string
  requestContextAttribute?: string
  exposePathVariables?: boolean
  exposeContextBeansAsAttributes?: boolean
  exposedContextBeanNames?: Array<string>
  beanName?: string
  url?: string
  contextRelative?: boolean
  http10Compatible?: boolean
  exposeModelAttributes?: boolean
  encodingScheme?: string
  statusCode?: DefaultHttpStatusCode | HttpStatus
  expandUriTemplateVariables?: boolean
  propagateQueryParams?: boolean
  hosts?: Array<string>
  redirectView?: boolean
  propagateQueryProperties?: boolean
  attributesCSV?: string
  attributes?: {
    [key: string]: string
  }
}

export type ServletContextWritable = {
  classLoader?: {
    name?: string
    registeredAsParallelCapable?: boolean
    parent?: {
      name?: string
      registeredAsParallelCapable?: boolean
      unnamedModule?: {
        name?: string
        descriptor?: {
          open?: boolean
          automatic?: boolean
        }
        named?: boolean
        annotations?: Array<unknown>
        declaredAnnotations?: Array<unknown>
        packages?: Array<string>
        nativeAccessEnabled?: boolean
        layer?: unknown
      }
      definedPackages?: Array<{
        name?: string
        sealed?: boolean
        annotations?: Array<unknown>
        declaredAnnotations?: Array<unknown>
        specificationTitle?: string
        specificationVersion?: string
        specificationVendor?: string
        implementationTitle?: string
        implementationVersion?: string
        implementationVendor?: string
      }>
      defaultAssertionStatus?: boolean
    }
    unnamedModule?: {
      name?: string
      descriptor?: {
        open?: boolean
        automatic?: boolean
      }
      named?: boolean
      annotations?: Array<unknown>
      declaredAnnotations?: Array<unknown>
      packages?: Array<string>
      nativeAccessEnabled?: boolean
      layer?: unknown
    }
    definedPackages?: Array<{
      name?: string
      sealed?: boolean
      annotations?: Array<unknown>
      declaredAnnotations?: Array<unknown>
      specificationTitle?: string
      specificationVersion?: string
      specificationVendor?: string
      implementationTitle?: string
      implementationVersion?: string
      implementationVendor?: string
    }>
    defaultAssertionStatus?: boolean
  }
  majorVersion?: number
  minorVersion?: number
  initParameterNames?: unknown
  contextPath?: string
  requestCharacterEncoding?: string
  responseCharacterEncoding?: string
  effectiveSessionTrackingModes?: Array<"COOKIE" | "URL" | "SSL">
  defaultSessionTrackingModes?: Array<"COOKIE" | "URL" | "SSL">
  effectiveMinorVersion?: number
  effectiveMajorVersion?: number
  sessionCookieConfig?: SessionCookieConfig
  sessionTrackingModes?: Array<"COOKIE" | "URL" | "SSL">
  filterRegistrations?: {
    [key: string]: FilterRegistration
  }
  servletContextName?: string
  servletRegistrations?: {
    [key: string]: ServletRegistration
  }
  jspConfigDescriptor?: JspConfigDescriptor
  serverInfo?: string
  sessionTimeout?: number
  virtualServerName?: string
  attributeNames?: unknown
}

export type CheckUpdateData = {
  body?: never
  path?: never
  query?: never
  url: "/api/public/local/cicd/check"
}

export type CheckUpdateResponses = {
  /**
   * OK
   */
  200: UpdateCheckResponse
}

export type CheckUpdateResponse =
  CheckUpdateResponses[keyof CheckUpdateResponses]

export type CheckUpdate1Data = {
  body?: never
  path: {
    target: string
    arch: string
    currentVersion: string
  }
  query?: never
  url: "/api/public/desktop/cicd/{target}/{arch}/{currentVersion}"
}

export type CheckUpdate1Responses = {
  /**
   * OK
   */
  200: TauriUpdateResponse
}

export type CheckUpdate1Response =
  CheckUpdate1Responses[keyof CheckUpdate1Responses]

export type DesktopLoginData = {
  body?: never
  path?: never
  query: {
    port: number
  }
  url: "/api/public/auth/desktop"
}

export type DesktopLoginResponses = {
  /**
   * OK
   */
  200: RedirectView
}

export type DesktopLoginResponse =
  DesktopLoginResponses[keyof DesktopLoginResponses]
