// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {})
}

export type UpdateRawJsonRequest = {
  rawJson?: string
}

export type CreateRequest = {
  serviceName?: string
  rawJson?: string
}

export type CreateApiKeyRequest = {
  name?: string
  expiresAt?: string
}

export type ApiKeyDto = {
  id?: string
  ownerId?: UserId
  name?: string
  createdAt?: string
  expiresAt?: string
  lastUsedAt?: string
  revoked?: boolean
  valid?: boolean
}

export type UserId = unknown

export type OpenApiDocSummary = {
  id?: number
  ownerId?: string
  serviceName?: string
  version?: number
  hash?: string
}

export type OpenApiSummaryDto = {
  title?: string
  version?: string
  description?: string
  totalEndpoints?: number
  tags?: Array<string>
}

export type EndpointDto = {
  summary?: EndpointSummaryDto
  endpoints?: Array<EndpointItemDto>
}

export type EndpointItemDto = {
  path?: string
  method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS"
  operationId?: string
  summary?: string
  description?: string
  parameters?: Array<EndpointParameter>
  requestBody?: EndpointRequestBodyDto
  responses?: Array<EndpointResponseBodyDto>
  tags?: Array<string>
}

export type EndpointParameter = {
  name?: string
  location?: "PATH" | "QUERY" | "HEADER" | "COOKIE"
  type?: string
  required?: boolean
}

export type EndpointRequestBodyDto = {
  mediaType?: string
  schemaJson?: string
  required?: boolean
}

export type EndpointResponseBodyDto = {
  statusCode?: number
  mediaType?: string
  schemaJson?: string
  description?: string
}

export type EndpointSummaryDto = {
  docId?: OpenApiDocId
  totalEndpoints?: number
}

export type OpenApiDocId = {
  value?: number
}

export type UserDto = {
  id?: UserId
  name?: string
  email?: string
  picture?: string
  role?: "USER" | "ADMIN"
  createdAt?: string
  lastLoginAt?: string
}

export type UpdateData = {
  body: UpdateRawJsonRequest
  path: {
    id: number
  }
  query?: never
  url: "/api/openapi-docs/{id}"
}

export type UpdateResponses = {
  /**
   * OK
   */
  200: unknown
}

export type ListAllData = {
  body?: never
  path?: never
  query?: never
  url: "/api/openapi-docs"
}

export type ListAllResponses = {
  /**
   * OK
   */
  200: Array<OpenApiDocSummary>
}

export type ListAllResponse = ListAllResponses[keyof ListAllResponses]

export type CreateData = {
  body: CreateRequest
  path?: never
  query?: never
  url: "/api/openapi-docs"
}

export type CreateResponses = {
  /**
   * OK
   */
  200: unknown
}

export type ListData = {
  body?: never
  path?: never
  query?: never
  url: "/api/api-keys"
}

export type ListResponses = {
  /**
   * OK
   */
  200: Array<ApiKeyDto>
}

export type ListResponse = ListResponses[keyof ListResponses]

export type Create1Data = {
  body: CreateApiKeyRequest
  path?: never
  query?: never
  url: "/api/api-keys"
}

export type Create1Responses = {
  /**
   * OK
   */
  200: ApiKeyDto
}

export type Create1Response = Create1Responses[keyof Create1Responses]

export type RevokeData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/api-keys/{id}/revoke"
}

export type RevokeResponses = {
  /**
   * OK
   */
  200: unknown
}

export type GetSummaryData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: "/api/openapi-docs/{id}/summary"
}

export type GetSummaryResponses = {
  /**
   * OK
   */
  200: OpenApiSummaryDto
}

export type GetSummaryResponse = GetSummaryResponses[keyof GetSummaryResponses]

export type GetRawJsonData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: "/api/openapi-docs/{id}/raw"
}

export type GetRawJsonResponses = {
  /**
   * OK
   */
  200: string
}

export type GetRawJsonResponse = GetRawJsonResponses[keyof GetRawJsonResponses]

export type GetEndpointsData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: "/api/openapi-docs/{id}/endpoints"
}

export type GetEndpointsResponses = {
  /**
   * OK
   */
  200: EndpointDto
}

export type GetEndpointsResponse =
  GetEndpointsResponses[keyof GetEndpointsResponses]

export type CicdSampleData = {
  body?: never
  path?: never
  query?: never
  url: "/api/openapi-docs/cicd-sample"
}

export type CicdSampleResponses = {
  /**
   * OK
   */
  200: string
}

export type CicdSampleResponse = CicdSampleResponses[keyof CicdSampleResponses]

export type UserData = {
  body?: never
  path?: never
  query?: never
  url: "/api/auth/user"
}

export type UserResponses = {
  /**
   * OK
   */
  200: UserDto
}

export type UserResponse = UserResponses[keyof UserResponses]

export type AuthStatusData = {
  body?: never
  path?: never
  query?: never
  url: "/api/auth/status"
}

export type AuthStatusResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: {
      [key: string]: unknown
    }
  }
}

export type AuthStatusResponse = AuthStatusResponses[keyof AuthStatusResponses]

export type DeleteData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/api-keys/{id}"
}

export type DeleteResponses = {
  /**
   * OK
   */
  200: unknown
}
