// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query"

import { client } from "../client.gen.ts"
import {
  authStatus,
  cicdSample,
  create,
  create1,
  delete_,
  getEndpoints,
  getRawJson,
  getSummary,
  list,
  listAll,
  type Options,
  revoke,
  update,
  user,
} from "../sdk.gen.ts"
import type {
  AuthStatusData,
  AuthStatusResponse,
  CicdSampleData,
  CicdSampleResponse,
  Create1Data,
  Create1Response,
  CreateData,
  DeleteData,
  GetEndpointsData,
  GetEndpointsResponse,
  GetRawJsonData,
  GetRawJsonResponse,
  GetSummaryData,
  GetSummaryResponse,
  ListAllData,
  ListAllResponse,
  ListData,
  ListResponse,
  RevokeData,
  UpdateData,
  UserData,
  UserResponse,
} from "../types.gen.ts"

export const updateMutation = (
  options?: Partial<Options<UpdateData>>
): UseMutationOptions<unknown, DefaultError, Options<UpdateData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<UpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await update({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const listAllQueryKey = (options?: Options<ListAllData>) =>
  createQueryKey("listAll", options)

export const listAllOptions = (options?: Options<ListAllData>) =>
  queryOptions<
    ListAllResponse,
    DefaultError,
    ListAllResponse,
    ReturnType<typeof listAllQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listAllQueryKey(options),
  })

export const createMutation = (
  options?: Partial<Options<CreateData>>
): UseMutationOptions<unknown, DefaultError, Options<CreateData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<CreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await create({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listQueryKey = (options?: Options<ListData>) =>
  createQueryKey("list", options)

export const listOptions = (options?: Options<ListData>) =>
  queryOptions<
    ListResponse,
    DefaultError,
    ListResponse,
    ReturnType<typeof listQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await list({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listQueryKey(options),
  })

export const create1Mutation = (
  options?: Partial<Options<Create1Data>>
): UseMutationOptions<Create1Response, DefaultError, Options<Create1Data>> => {
  const mutationOptions: UseMutationOptions<
    Create1Response,
    DefaultError,
    Options<Create1Data>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await create1({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const revokeMutation = (
  options?: Partial<Options<RevokeData>>
): UseMutationOptions<unknown, DefaultError, Options<RevokeData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<RevokeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await revoke({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getSummaryQueryKey = (options: Options<GetSummaryData>) =>
  createQueryKey("getSummary", options)

export const getSummaryOptions = (options: Options<GetSummaryData>) =>
  queryOptions<
    GetSummaryResponse,
    DefaultError,
    GetSummaryResponse,
    ReturnType<typeof getSummaryQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSummary({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getSummaryQueryKey(options),
  })

export const getRawJsonQueryKey = (options: Options<GetRawJsonData>) =>
  createQueryKey("getRawJson", options)

export const getRawJsonOptions = (options: Options<GetRawJsonData>) =>
  queryOptions<
    GetRawJsonResponse,
    DefaultError,
    GetRawJsonResponse,
    ReturnType<typeof getRawJsonQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRawJson({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getRawJsonQueryKey(options),
  })

export const getEndpointsQueryKey = (options: Options<GetEndpointsData>) =>
  createQueryKey("getEndpoints", options)

export const getEndpointsOptions = (options: Options<GetEndpointsData>) =>
  queryOptions<
    GetEndpointsResponse,
    DefaultError,
    GetEndpointsResponse,
    ReturnType<typeof getEndpointsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEndpoints({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getEndpointsQueryKey(options),
  })

export const cicdSampleQueryKey = (options?: Options<CicdSampleData>) =>
  createQueryKey("cicdSample", options)

export const cicdSampleOptions = (options?: Options<CicdSampleData>) =>
  queryOptions<
    CicdSampleResponse,
    DefaultError,
    CicdSampleResponse,
    ReturnType<typeof cicdSampleQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await cicdSample({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: cicdSampleQueryKey(options),
  })

export const userQueryKey = (options?: Options<UserData>) =>
  createQueryKey("user", options)

export const userOptions = (options?: Options<UserData>) =>
  queryOptions<
    UserResponse,
    DefaultError,
    UserResponse,
    ReturnType<typeof userQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await user({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: userQueryKey(options),
  })

export const authStatusQueryKey = (options?: Options<AuthStatusData>) =>
  createQueryKey("authStatus", options)

export const authStatusOptions = (options?: Options<AuthStatusData>) =>
  queryOptions<
    AuthStatusResponse,
    DefaultError,
    AuthStatusResponse,
    ReturnType<typeof authStatusQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: authStatusQueryKey(options),
  })

export const deleteMutation = (
  options?: Partial<Options<DeleteData>>
): UseMutationOptions<unknown, DefaultError, Options<DeleteData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<DeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await delete_({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
