// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from "@tanstack/react-query"

import { client } from "../client.gen.ts"
import {
  checkUpdate,
  checkUpdate1,
  desktopLogin,
  type Options,
} from "../sdk.gen.ts"
import type {
  CheckUpdate1Data,
  CheckUpdate1Response,
  CheckUpdateData,
  CheckUpdateResponse,
  DesktopLoginData,
  DesktopLoginResponse,
} from "../types.gen.ts"

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const checkUpdateQueryKey = (options?: Options<CheckUpdateData>) =>
  createQueryKey("checkUpdate", options)

export const checkUpdateOptions = (options?: Options<CheckUpdateData>) =>
  queryOptions<
    CheckUpdateResponse,
    DefaultError,
    CheckUpdateResponse,
    ReturnType<typeof checkUpdateQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await checkUpdate({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: checkUpdateQueryKey(options),
  })

export const checkUpdate1QueryKey = (options: Options<CheckUpdate1Data>) =>
  createQueryKey("checkUpdate1", options)

export const checkUpdate1Options = (options: Options<CheckUpdate1Data>) =>
  queryOptions<
    CheckUpdate1Response,
    DefaultError,
    CheckUpdate1Response,
    ReturnType<typeof checkUpdate1QueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await checkUpdate1({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: checkUpdate1QueryKey(options),
  })

export const desktopLoginQueryKey = (options: Options<DesktopLoginData>) =>
  createQueryKey("desktopLogin", options)

export const desktopLoginOptions = (options: Options<DesktopLoginData>) =>
  queryOptions<
    DesktopLoginResponse,
    DefaultError,
    DesktopLoginResponse,
    ReturnType<typeof desktopLoginQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await desktopLogin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: desktopLoginQueryKey(options),
  })
